apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-cart-service
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
        - name: shopping-cart-service
          image: services_shopping-cart-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-secret
                  key: JWT_SECRET
            - name: PORT
              value: 5002
            - name: POSTGRES_URI
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart-service-config
                  key: POSTGRES_URI
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart-service-config
                  key: RABBITMQ_URL
            - name: DEFAULT_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart-service-config
                  key: DEFAULT_DB_URI
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart-service-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart-service-config
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart-service-config
                  key: PAYMENT_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart-service-config
                  key: USER_SERVICE_URL
