apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: takemi085/laskak:product-service
          ports:
            - containerPort: 5001
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: JWT_SECRET
            - name: PORT
              value: "5001"
            - name: POSTGRES_URI
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: POSTGRES_URI
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: RABBITMQ_URL
            - name: DEFAULT_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: DEFAULT_DB_URI
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: PAYMENT_SERVICE_URL
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: CART_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: USER_SERVICE_URL
