apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  POSTGRES_URI: postgres://sayib:Sinat@postgresql:5432/payments_db
  RABBITMQ_URL: amqp://rabbitmq:5672
  DEFAULT_DB_URI: postgres://sayib:Sinat@postgresql:5432/postgres
  PRODUCT_SERVICE_URL: http://product-service:5001/api/products
  ORDER_SERVICE_URL: http://order-service:5003/api/order
  USER_SERVICE_URL: http://user-service:5000/api/users
  CART_SERVICE_URL: http://shopping-cart-service:5002/api/cart