apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30004
  selector:
    app: payment-service
  type: NodePort
