apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: takemi085/laskak:user-service
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
            - name: PORT
              value: 5000
            - name: POSTGRES_URI
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: POSTGRES_URI
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: RABBITMQ_URL
            - name: DEFAULT_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: DEFAULT_DB_URI
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: PAYMENT_SERVICE_URL
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: CART_SERVICE_URL
