apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: services_order-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: JWT_SECRET
            - name: PORT
              value: 5003
            - name: POSTGRES_URI
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: POSTGRES_URI
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: RABBITMQ_URL
            - name: DEFAULT_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: DEFAULT_DB_URI
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: PRODUCT_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: USER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: PAYMENT_SERVICE_URL
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: CART_SERVICE_URL
